"""Write the generated documentation pages from the code.

docs/inputs.md comes from the pydantic models in good/schema.py and
docs/assumptions.md from good.migrate.ASSUMPTIONS. tests/test_docs.py fails
when the committed pages are out of date; rerun this script after changing
either source:

    python scripts/generate_docs.py
"""

import math
import sys
from pathlib import Path

from good import migrate, schema

DOCS = Path(__file__).resolve().parent.parent / "docs"

SECTIONS = [
    ("Region", schema.RegionParams, "Node class. One per balancing region."),
    ("Link", schema.LinkParams, "Edge class. Holds the transmission lines from its source region to its target."),
    ("Producer", schema.ProducerParams, "Asset class for generators, including wind, solar and hydro."),
    ("Store", schema.StoreParams, "Asset class for storage."),
    ("Load", schema.LoadParams, "Asset class for demand."),
    ("Transmission", schema.TransmissionParams, "Line class for directed transfer paths."),
    ("Portfolio_Standard", schema.PortfolioStandardParams, "Policy: share of generation from included assets."),
    ("Capacity_Target", schema.CapacityTargetParams, "Policy: minimum capacity of included assets."),
    ("Reserve_Margin", schema.ReserveMarginParams, "Policy: credited capacity above peak demand."),
]


def _format(value):

    if isinstance(value, float) and math.isinf(value):

        return "inf"

    if value is None:

        return "unset"

    if isinstance(value, str) and value != "required":

        return f"`{value}`"

    return f"`{value}`" if value != "required" else "**required**"


def inputs_page():

    lines = [
        "# Input reference",
        "",
        "<!-- Generated by scripts/generate_docs.py from good/schema.py. Do not edit by hand. -->",
        "",
        "Every component validates its inputs against these fields when it is added to a network.",
        "Units are listed in [Units](units.md). Any other key (for example `fuel`, `jurisdiction` or",
        "`co2`) is kept as a free-form attribute that policy filters can use.",
        "",
    ]

    for name, model, blurb in SECTIONS:

        lines += [f"## {name}", "", blurb, ""]
        rows = schema.field_table(model)

        if rows:

            lines += ["| Field | Default | Meaning |", "|---|---|---|"]
            lines += [f"| `{field}` | {_format(default)} | {description} |" for field, default, description in rows]

        else:

            lines.append("No fields beyond free-form attributes.")

        legacy = getattr(model, "LEGACY", {})

        if legacy:

            lines += ["", "Removed in 2.0 (rejected with an explanation):", ""]
            lines += [f"* `{key}`: {hint}" for key, hint in legacy.items()]

        lines.append("")

    return "\n".join(lines)


def assumptions_page():

    lines = [
        "# Data assumptions",
        "",
        "<!-- Generated by scripts/generate_docs.py from good/migrate.py. Do not edit by hand. -->",
        "",
        "`good.migrate.from_v1()` introduces the values below when converting GOOD 1.x graphs.",
        "Values marked PLACEHOLDER or ASSUMPTION should be reviewed before results are published.",
        "Pass a modified copy of `good.migrate.ASSUMPTIONS` to `from_v1(graph, assumptions=...)`",
        "to change them.",
        "",
    ]

    for key, spec in migrate.ASSUMPTIONS.items():

        lines += [f"## `{key}`", ""]

        values = {k: v for k, v in spec.items() if k != "source"}

        if values:

            lines += ["| Field | Value |", "|---|---|"]
            lines += [f"| `{k}` | {v:,.6g} |" if isinstance(v, float) else f"| `{k}` | {v} |" for k, v in values.items()]
            lines.append("")

        lines += [f"Source: {spec.get('source', '')}", ""]

    return "\n".join(lines)


PAGES = {"inputs.md": inputs_page, "assumptions.md": assumptions_page}


def main(check=False):

    stale = []

    for name, render in PAGES.items():

        path = DOCS / name
        text = render()

        if check:

            if not path.exists() or path.read_text() != text:

                stale.append(name)

        else:

            path.write_text(text)

    return stale


if __name__ == "__main__":

    stale = main(check="--check" in sys.argv)

    if stale:

        sys.exit(f"Out of date: {', '.join(stale)}. Run python scripts/generate_docs.py")
